//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetail
    {
        public string Item_Name { get; set; }
        public int Item_Price { get; set; }
        public string Image_Name { get; set; }
        public string Item_Description { get; set; }
    }
}
