//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaCartWebApp.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartDataContract.ItemDetails", Namespace="http://schemas.datacontract.org/2004/07/CartService")]
    [System.SerializableAttribute()]
    public partial class ShoppingCartDataContractItemDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Image_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image_Name {
            get {
                return this.Image_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Image_NameField, value) != true)) {
                    this.Image_NameField = value;
                    this.RaisePropertyChanged("Image_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Description {
            get {
                return this.Item_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_DescriptionField, value) != true)) {
                    this.Item_DescriptionField = value;
                    this.RaisePropertyChanged("Item_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Name {
            get {
                return this.Item_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_NameField, value) != true)) {
                    this.Item_NameField = value;
                    this.RaisePropertyChanged("Item_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Price {
            get {
                return this.Item_PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_PriceField, value) != true)) {
                    this.Item_PriceField = value;
                    this.RaisePropertyChanged("Item_Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemDetails", ReplyAction="http://tempuri.org/IService1/GetItemDetailsResponse")]
        TeaCartWebApp.ServiceReference2.ShoppingCartDataContractItemDetails[] GetItemDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemDetails", ReplyAction="http://tempuri.org/IService1/GetItemDetailsResponse")]
        System.Threading.Tasks.Task<TeaCartWebApp.ServiceReference2.ShoppingCartDataContractItemDetails[]> GetItemDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addItem", ReplyAction="http://tempuri.org/IService1/addItemResponse")]
        bool addItem(TeaCartWebApp.ServiceReference2.ShoppingCartDataContractItemDetails itemDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addItem", ReplyAction="http://tempuri.org/IService1/addItemResponse")]
        System.Threading.Tasks.Task<bool> addItemAsync(TeaCartWebApp.ServiceReference2.ShoppingCartDataContractItemDetails itemDetails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TeaCartWebApp.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TeaCartWebApp.ServiceReference2.IService1>, TeaCartWebApp.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TeaCartWebApp.ServiceReference2.ShoppingCartDataContractItemDetails[] GetItemDetails() {
            return base.Channel.GetItemDetails();
        }
        
        public System.Threading.Tasks.Task<TeaCartWebApp.ServiceReference2.ShoppingCartDataContractItemDetails[]> GetItemDetailsAsync() {
            return base.Channel.GetItemDetailsAsync();
        }
        
        public bool addItem(TeaCartWebApp.ServiceReference2.ShoppingCartDataContractItemDetails itemDetails) {
            return base.Channel.addItem(itemDetails);
        }
        
        public System.Threading.Tasks.Task<bool> addItemAsync(TeaCartWebApp.ServiceReference2.ShoppingCartDataContractItemDetails itemDetails) {
            return base.Channel.addItemAsync(itemDetails);
        }
    }
}
